### ISSUE TITLE
Equation 11 confusion

### ISSUE THREAD

**Issue by deklanw** [wuga214/NCE_Projected_LRec#38]
I'm not seeing how this code:

https://github.com/wuga214/NCE_Projected_LRec/blob/master/models/nceplrec.py#L11-L29

Corresponds to this

![image](https://user-images.githubusercontent.com/11601778/104072459-473f0e80-51d9-11eb-8700-46e6f15bfbea.png)

In particular, this term
![image](https://user-images.githubusercontent.com/11601778/104072710-ef54d780-51d9-11eb-92a2-781ed0881d87.png)

is a constant, right? The number of interactions for each item, summed over items... so the total number of interactions, i.e. the number of nonzero entries? 

I see you have an unused variable here:

```python3
nnz = matrix.nnz
```

But, in the code, the corresponding part to equation 11 seems to be

```python3
values = np.maximum(np.log(rows/np.power(values, root)), 0)
```

where `rows` is an integer: the number of users.

What am I missing here?

**Comment by wuga214** [comment]
Hi deklanw,

The root in the code is not exactly the beta in the paper, but something like root = f(beta), where f is a linear function.

As you have seen, the nominator here is just a constant (the total number of ratings in the training set); another constant could replace it without changing the basic concept.  This is similar to what we do on the SVM models, where the margin could be set as r=1 to reduce the optimization complexity. 

We replace it with the number of rows because it could guarantee, log() >=0, so we can sufficiently distinguish rated entry from those of zeros.

As long as we start tuning the hyper-parameters, their behaviour should be similar. The difference to the user is if we want to tune from 0.8-1.3 or from 800000 to 1300000.

**Comment by deklanw** [comment]
@wuga214 Thanks. That makes sense. A bit tricky, I didn't even notice initially while reading that that value was a constant.

But, I think I got it now.
